tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed-variant": "#004e5c",
                "on-tertiary-fixed": "#001f26",
                "error-container": "#93000a",
                "tertiary-fixed": "#acedff",
                "primary-container": "#8f2de6",
                "on-primary-container": "#f2dfff",
                "primary-fixed-dim": "#ddb8ff",
                "on-primary": "#490080",
                "secondary-fixed-dim": "#adc6ff",
                "on-primary-fixed-variant": "#6800b4",
                "on-secondary-fixed-variant": "#004395",
                "inverse-surface": "#dae2fd",
                "tertiary-container": "#007184",
                "inverse-primary": "#861fdd",
                "tertiary": "#4cd7f6",
                "surface-container-highest": "#2d3449",
                "on-surface": "#dae2fd",
                "surface-bright": "#31394d",
                "on-background": "#dae2fd",
                "surface-dim": "#0b1326",
                "surface-container": "#171f33",
                "inverse-on-surface": "#283044",
                "surface-variant": "#2d3449",
                "secondary": "#adc6ff",
                "secondary-container": "#0566d9",
                "outline-variant": "#4a4455",
                "surface-container-lowest": "#060e20",
                "on-error": "#690005",
                "on-tertiary": "#003640",
                "background": "#0b1326",
                "error": "#ffb4ab",
                "on-surface-variant": "#ccc3d8",
                "primary-fixed": "#f0dbff",
                "on-tertiary-container": "#b7efff",
                "on-primary-fixed": "#2c0051",
                "outline": "#958da1",
                "on-secondary-fixed": "#001a42",
                "surface-tint": "#ddb8ff",
                "on-error-container": "#ffdad6",
                "secondary-fixed": "#d8e2ff",
                "primary": "#ddb8ff",
                "on-secondary-container": "#e6ecff",
                "surface": "#0b1326",
                "tertiary-fixed-dim": "#4cd7f6",
                "surface-container-high": "#222a3d",
                "surface-container-low": "#131b2e",
                "on-secondary": "#002e6a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            }
        },
    },
};
